In [74]:
i = 10

In [75]:
type(i)

int

# 設定

In [3]:
%matplotlib inline
import cv2
print(cv2.__version__)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from scipy import stats
def cv_imread(filePath):
    cv_img = cv2.imdecode(np.fromfile(filePath, dtype=np.uint8), cv2.IMREAD_COLOR)
    return cv_img
import threading
import keyboard
import time
import pyzbar.pyzbar as pyzbar

4.5.1


# 圖片

In [78]:
img = cv_imread(r'C:\\suponien\\work\\螢幕預設.jpg')

In [82]:
cv2.imshow('img', img)
print(type(int(img[0][0][0])))
print(type(i))
cv2.waitKey(5000)  # ms
cv2.destroyWindow('img')

<class 'int'>
<class 'int'>


### 1. 圖片大小

In [47]:
img = cv2.resize(img, (200,200))
cv2.imshow('img', img)

cv2.waitKey(0)  # ms
cv2.destroyWindow('img')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
# 倍數
img = cv2.resize(img, (0,0), fx = 2, fy = 2)
cv2.imshow('img', img)
cv2.waitKey(0)  # ms
cv2.destroyWindow('img')

# 影片

In [3]:
cap = cv2.VideoCapture('testvideo.mp4')

In [37]:
# 播影片
cap = cv2.VideoCapture('testvideo.mp4')
play = 1
while True:
    if play:
        ret, frame = cap.read()  #回傳取得是否成功(boolin), 下一張圖片
        if ret:
            cv2.imshow('video', cv2.resize(frame, (0,0), fx = 0.5, fy = 0.5))
            print(frame)
        else: break

    #影片操作
    key = cv2.waitKey(1)
    if key == -1:
        continue
    elif key == ord('q') or key == 27: # Esc
        print('break')
        break
    elif key == 13: # Enter
        print('play / pause')
        play = play ^ 1
cap.release()
cv2.destroyWindow('video')
#p
    


[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[144 144 144]
  [144 144 144]
  [144 144 144]
  ..

### 1. 同步操作

In [4]:
play = 1
end = 1
ret = 1
# 影片
def function(videopath):
    cap = cv2.VideoCapture(videopath)
    global play
    global end
    global ret
    while True:
        if play:
            ret, frame = cap.read()  #回傳取得是否成功(boolin), 下一張圖片
            if ret:
                cv2.imshow('video', cv2.resize(frame, (0,0), fx = 0.5, fy = 0.5))
            else: break
#         time.sleep(0.001)
    end = 0
    cap.release()
    cv2.destroyWindow('video')
    
# 影片操作
def manipulation():
    print('hahaha')
    global play
    global end
    global ret
    while end:
        key = keyboard.read_key()
        if key == 'esc': # Esc
            ret = 0
            print('break')
            break
        elif key == 'enter': # Enter
            print('play / pause')
            play = play ^ 1

In [5]:
threads = []
play = 1
end = 1
t = threading.Thread(target = function , args = ('testvideo.mp4',))
threads.append(t)
t.start()
# t.join()
t = threading.Thread(target=manipulation , args=())
threads.append(t)
t.start()
# t.join()


hahaha
play / pause


## 攝像頭

In [4]:
# 播影片
cap = cv2.VideoCapture(0)
play = 1
while cap.isOpened():
    if play:
        ret, frame = cap.read()  #回傳取得是否成功(boolin), 下一張圖片
        if ret:
#             cv2.imshow('video', cv2.resize(frame, (0,0), fx = 0.5, fy = 0.5))
            cv2.imshow('video', frame)
        else: 
            print("failed")
            break

    #影片操作
    key = cv2.waitKey(1)
    if key == -1:
        continue
    elif key == ord('q') or key == 27: # Esc
        print('break')
        break
    elif key == 13: # Enter
        print('play / pause')
        play = play ^ 1
cap.release()
cv2.destroyWindow('video')

#p
    


break


## 空白照片

In [22]:
img = np.empty((300,300,3), np.uint8)
for row in range(300):
    for col in range(300):
        img[row][col] = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyWindow('img')

#### 1.加上噪點

In [18]:
img = cv_imread(r'C:\\suponien\\work\\螢幕預設.jpg')
# img = np.empty((300,300,3), np.uint8)
for row in range(300):
    for col in range(img.shape[1]):
        img[row][col] = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyWindow('img')

(732, 1419, 3)

### 2. 轉為灰階圖片

In [4]:
img = cv_imread(r'C:\\suponien\\work\\螢幕預設.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('img', gray)
cv2.waitKey(0)
cv2.destroyWindow('img')

### 3. 模糊

In [7]:
blur = cv2.GaussianBlur(img, (11, 11), 10)  #(number, number)都要是奇數
cv2.imshow('img', blur)
cv2.waitKey(0)
cv2.destroyWindow('img')

### 4. 圖片邊緣

In [20]:
canny = cv2.Canny(img, 150, 200)
cv2.imshow('img', canny)
cv2.waitKey(0)
cv2.destroyWindow('img')

### 5. 圖片膨脹

In [14]:
kernel = np.ones((10, 10), np.uint8)

In [19]:
dilate = cv2.dilate(canny, kernel, iterations = 2)
cv2.imshow('img', dilate)
cv2.waitKey(0)
cv2.destroyWindow('img')

### 6. 線條變細

In [24]:
kernel = np.ones((10, 10), np.uint8)

In [27]:
erode = cv2.erode(dilate, kernel, iterations = 1)
cv2.imshow('img', erode)
cv2.waitKey(0)
cv2.destroyWindow('img')

# 畫形狀&寫字

In [29]:
img = np.zeros((600, 600, 3), np.uint8)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyWindow('img')

In [32]:
img = np.zeros((600, 600, 3), np.uint8)
cv2.line(img, (0, 0), (img.shape[1], img.shape[0]), (255, 0, 0))  #起始點，終點，顏色
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyWindow('img')

In [36]:
img = np.zeros((600, 600, 3), np.uint8)
cv2.rectangle(img, (0, 0), (400, 300), (50, 50, 0), cv2.FILLED)  #圖片，左上角點，右上角點，顏色，粗度
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyWindow('img')

In [37]:
img = np.zeros((600, 600, 3), np.uint8)
cv2.circle(img, (400, 300), 20, (50, 50, 0), cv2.FILLED)  #圖片，圓心，半徑，顏色，粗度
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyWindow('img')

In [41]:
img = np.zeros((600, 600, 3), np.uint8)
cv2.putText(img, 'hello', (200, 200), cv2.FONT_HERSHEY_DUPLEX, 5, (50, 50, 80), 2)  #文字，座標，字體，大小，顏色，粗度(不能寫中文)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyWindow('img')

# 偵測顏色

In [14]:
def empty(v):
    pass

img = cv_imread(r'C:\\suponien\\work\\python\\海綿.jfif')
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)


cv2.namedWindow('Trackbar')
cv2.resizeWindow('Trackbar', 640, 480)
cv2.createTrackbar('hue Min', 'Trackbar', 0, 179, empty)  # 0~179
cv2.createTrackbar('hue Max', 'Trackbar', 179, 179, empty)
cv2.createTrackbar('sat Min', 'Trackbar', 0, 255, empty)  # 0~255
cv2.createTrackbar('sat Max', 'Trackbar', 255, 255, empty)
cv2.createTrackbar('val Min', 'Trackbar', 128, 255, empty)  # 0~255
cv2.createTrackbar('val Max', 'Trackbar', 241, 255, empty)

# cv2.imshow('Trackbar')
# cv2.waitKey(0)
while True:
    h_min = cv2.getTrackbarPos('hue Min', 'Trackbar')
    h_max = cv2.getTrackbarPos('hue Max', 'Trackbar')
    s_min = cv2.getTrackbarPos('sat Min', 'Trackbar')
    s_max = cv2.getTrackbarPos('sat Max', 'Trackbar')
    v_min = cv2.getTrackbarPos('val Min', 'Trackbar')
    v_max = cv2.getTrackbarPos('val Max', 'Trackbar')
    
    lower = np.array([h_min, s_min, v_min])
    upper = np.array([h_max, s_max, v_max])
    
    mask = cv2.inRange(hsv, lower, upper)
    result = cv2.bitwise_and(img, img, mask = mask)
    
    cv2.imshow('img', img)
    cv2.imshow('hsv', hsv)
    cv2.imshow('mask', mask)
    cv2.imshow('result', result)
    key = cv2.waitKey(1)
    if key == -1:
        continue
    elif key == ord('q') or key == 27: # Esc
        print('break')
        break


cv2.destroyWindow('img')
cv2.destroyWindow('hsv')
cv2.destroyWindow('Trackbar')
cv2.destroyWindow('mask')

break


In [22]:
cv2.destroyAllWindows()


# 輪廓檢測


In [22]:
img = cv_imread(r'C:\\suponien\\work\\python\\海綿.jfif')
img = cv2.resize(img, (0,0), fx = 3, fy = 3)
imgContour = img.copy()
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
canny = cv2.Canny(img, 80, 120)
contours, hierachy = cv2.findContours(canny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

for cnt in contours:
    cv2.drawContours(imgContour, cnt, -1, (0, 0, 0), 4)
    print(cv2.contourArea(cnt))
    area = cv2.contourArea(cnt)
#     print(cv2.arcLength(cnt, True))
    if area > 50:
        peri = cv2.arcLength(cnt, True)
        vertices = cv2.approxPolyDP(cnt, peri * 0.02, True)
        corners = len(vertices)
        print(vertices)
        x, y, w, h, = cv2.boundingRect(vertices)
        cv2.rectangle(imgContour, (x, y), (x+w, y+h), (0, 255, 0), 4)
        if corners == 3:
            cv2.putText(imgContour, 'triangle', (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
        elif corners == 4:
            cv2.putText(imgContour, 'rectangle', (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
        elif corners == 5:
            cv2.putText(imgContour, 'pentagon', (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
        elif corners >= 6:
            cv2.putText(imgContour, 'circle', (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
    
    
cv2.imshow('canny', canny)
cv2.imshow('imgContour', imgContour)
cv2.waitKey(0)
cv2.destroyAllWindows()

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.5
1.0
1.5
1.0
8.5
0.5
1.0
2.0
13.0
1.0
2.0
1.5
4.0
4.5
0.0
13.5
0.5
0.0
13.0
2.0
2.0
0.0
0.5
1.0
10.0
0.0
2.5
1.5
0.0
1.5
3.0
1.5
1.0
1.0
6.5
15.5
0.5
3.0
1.5
2.5
0.0
0.0
0.0
1.0
12.5
1.5
2.0
0.0
27.0
0.0
0.0
0.0
1.5
0.0
0.5
0.0
0.5
0.0
1.0
1.0
0.0
0.0
10.0
0.0
0.0
1.0
0.0
0.5
42.0
0.5
26.0
0.0
12.5
0.0
0.0
0.5
3.0
0.5
1.0
147.0
[[[130 265]]

 [[529 470]]]
0.0
3.5
0.0
27.0
0.0
11.0
0.0
189.5
[[[588 110]]

 [[741 191]]

 [[720 300]]

 [[544 472]]

 [[720 301]]

 [[741 191]]]
0.0
11.0
62.5
[[[312  33]]

 [[126 122]]

 [[132 264]]

 [[126 123]]]
22.0


# 人臉辨識

In [46]:
img = cv_imread('face.jfif')

In [47]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [54]:
faceCascade = cv2.CascadeClassifier('face_detect.xml')
faceRect = faceCascade.detectMultiScale(gray, 1.1, 3)

for (x, y, w, h) in faceRect:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0, 255, 0), 2)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 虛擬筆

In [96]:
def empty(v):
    pass
circleList = []
def draw(circleList):
    for i in circleList:
        cv2.circle(frame, (i[0], i[1]), 10, (255, 255, 255), cv2.FILLED)
    
    
# 播影片
color = [0,179,122,255,128,255]

cv2.namedWindow('Trackbar')
cv2.resizeWindow('Trackbar', 640, 480)
cv2.createTrackbar('hue Min', 'Trackbar', 0, 179, empty)  # 0~179
cv2.createTrackbar('hue Max', 'Trackbar', 179, 179, empty)
cv2.createTrackbar('sat Min', 'Trackbar', 130, 255, empty)  # 0~255
cv2.createTrackbar('sat Max', 'Trackbar', 255, 255, empty)
cv2.createTrackbar('val Min', 'Trackbar', 80, 255, empty)  # 0~255
cv2.createTrackbar('val Max', 'Trackbar', 150, 255, empty)
cap = cv2.VideoCapture(0)
play = 1
while cap.isOpened():
    h_min = cv2.getTrackbarPos('hue Min', 'Trackbar')
    h_max = cv2.getTrackbarPos('hue Max', 'Trackbar')
    s_min = cv2.getTrackbarPos('sat Min', 'Trackbar')
    s_max = cv2.getTrackbarPos('sat Max', 'Trackbar')
    v_min = cv2.getTrackbarPos('val Min', 'Trackbar')
    v_max = cv2.getTrackbarPos('val Max', 'Trackbar')
    
    lower = np.array([color[0], color[2], color[4]])
    upper = np.array([color[1], color[3], color[5]])
    
    
    
    if play:
        ret, frame = cap.read()  #回傳取得是否成功(boolin), 下一張圖片
        if ret:
            hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
            mask = cv2.inRange(hsv, lower, upper)
            result = cv2.bitwise_and(frame, frame, mask = mask)
            imgContour = result.copy()
            img = cv2.cvtColor(result, cv2.COLOR_BGR2GRAY)
            canny = cv2.Canny(img, 80, 120)
            contours, hierachy = cv2.findContours(canny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

            for cnt in contours:
                cv2.drawContours(imgContour, cnt, -1, (255, 255, 255), 4)
                area = cv2.contourArea(cnt)
            #     print(cv2.arcLength(cnt, True))
                if area > 300:
                    peri = cv2.arcLength(cnt, True)
                    vertices = cv2.approxPolyDP(cnt, peri * 0.02, True)
                    corners = len(vertices)
#                     print(vertices)
                    x, y, w, h, = cv2.boundingRect(vertices)
#                     cv2.rectangle(imgContour, (x, y), (x+w, y+h), (255, 255, 255), 4)
                    circleList.append([x+w//2, y])
#                     draw(circleList)
                    print(type(tuple(int(i) for i in frame[x+w//2][y])[0]))
                    cv2.circle(frame, (x+w//2, y), 10, tuple(int(i) for i in frame[x+w//2][y]), cv2.FILLED)
#             cv2.imshow('imgContour', imgContour)
            cv2.imshow('video', frame)
#             cv2.imshow('hsv', hsv)
#             cv2.imshow('mask', mask)
            cv2.imshow('result', result)
        else: break

    #影片操作
    key = cv2.waitKey(1)
    if key == -1:
        continue
    elif key == ord('q') or key == 27: # Esc
        print('break')
        break
    elif key == 13: # Enter
        print('play / pause')
        play = play ^ 1
cap.release()
cv2.destroyAllWindows()
#p
    


<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


IndexError: index 488 is out of bounds for axis 0 with size 480

In [97]:
cv2.destroyAllWindows()

# barcode

### 1. 圖片

#### 1.1 cv2套件

In [41]:
#設定變數
recursive = 70  # 比對幾次
mag = 3  # 初始倍率
zoom = 0.95 #每次縮放的倍率

barcode = cv2.barcode.BarcodeDetector() 
img = cv_imread(r'barcode_folder\\17729.jpg')
img = cv2.resize(img, (0,0), fx = mag, fy = mag)
cv2.imshow('img', img)
# for i in range(recursive):
#     img = cv2.resize(img, (0,0), fx = zoom, fy = zoom)
#     det = barcode.detect(img)
#     print(det)
decoded_info = []
for i in range(recursive):
    img = cv2.resize(img, (0,0), fx = zoom, fy = zoom)
#     ok, info, decoded_type, corners = barcode.detectAndDecode(img)
    ok, info, _, _ = barcode.detectAndDecode(img)
    if ok:
        decoded_info.append(info[0])
# print(decoded_info)
if len(decoded_info) != 0:
    print(stats.mode(decoded_info)[0][0])
else:
    print('no barcode detected')
cv2.waitKey(1000)
cv2.destroyWindow('img')

no barcode detected


#### 1.2 pyzbar套件

In [3]:
import pyzbar.pyzbar as pyzbar

In [41]:
# #設定變數
# recursive = 70  # 比對幾次
# mag = 3  # 初始倍率
# zoom = 0.95 #每次縮放的倍率
tt = 0
img = cv_imread(r'barcode_folder\\test3.jpg')
# img = cv2.resize(img, (0,0), fx = mag, fy = mag) #放大圖片
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) #轉灰
texts = pyzbar.decode(img)
for text in texts:
    if text.data.decode("utf-8"):
        tt = text.data.decode("utf-8")
print(tt)
# cv2.imshow('img', img)
# # for i in range(recursive):
# #     img = cv2.resize(img, (0,0), fx = zoom, fy = zoom)
# #     det = barcode.detect(img)
# #     print(det)
# decoded_info = []
# for i in range(recursive):
#     img = cv2.resize(img, (0,0), fx = zoom, fy = zoom)
# #     ok, info, decoded_type, corners = barcode.detectAndDecode(img)
#     ok, info, _, _ = barcode.detectAndDecode(img)
#     if ok:
#         decoded_info.append(info[0])
# # print(decoded_info)
# if len(decoded_info) != 0:
#     print(stats.mode(decoded_info)[0][0])
# else:
#     print('no barcode detected')
# cv2.waitKey(1000)
# cv2.destroyWindow('img')

2777736929


### 2. 影片

#### 2.1 cv2套件

In [7]:
barcode = cv2.barcode.BarcodeDetector()     
# 播影片
cap = cv2.VideoCapture(0)
play = 1
while cap.isOpened():
    if play:
        ret, frame = cap.read()  #回傳取得是否成功(boolin), 下一張圖片
        if ret:
            cv2.imshow('video', frame)
            ok, decoded_info, decoded_type, corners = barcode.detectAndDecode(frame)
            if ok:
                print(decoded_info)
        else: break
        key = cv2.waitKey(1)
        
    #影片操作
    key = cv2.waitKey(1)
    if key == -1:
        continue
    elif key == ord('q') or key == 27: # Esc
        print('break')
        break
    elif key == 13: # Enter
        print('play / pause')
        play = play ^ 1
cap.release()
cv2.destroyWindow('video')

break


#### 2.2 pyzbar套件

In [5]:
# 播影片

cap = cv2.VideoCapture(0)
play = 1
print(1)
while cap.isOpened():
    if play:
        ret, frame = cap.read()  #回傳取得是否成功(boolin), 下一張圖片
        if ret:
            cv2.imshow('video', frame)
            bar = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) #轉灰
            barcode = pyzbar.decode(bar)
            for text in barcode:
                if text.data.decode("utf-8"):
                    tt = text.data.decode("utf-8")
                    play = play ^ 1
                    print(tt)
        else: break
        
    #影片操作
    key = cv2.waitKey(1)
    if key == -1:
        continue
    elif key == ord('q') or key == 27: # Esc
        print('break')
        break
    elif key == 13: # Enter
        print('play / pause')
        play = play ^ 1
cap.release()
cv2.destroyWindow('video')

1
112421
play / pause
251211
break


In [17]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [101,  86,  77],
        [101,  86,  78],
        [100,  85,  77]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [101,  87,  79],
        [100,  88,  79],
        [ 99,  86,  78]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [100,  88,  79],
        [100,  88,  79],
        [ 98,  85,  77]],

       ...,

       [[ 74,  49,  27],
        [ 47,  27,  10],
        [ 53,  40,  27],
        ...,
        [ 70,  42,  23],
        [ 70,  42,  23],
        [ 68,  40,  21]],

       [[ 73,  47,  26],
        [ 50,  32,  15],
        [ 50,  40,  26],
        ...,
        [ 70,  42,  23],
        [ 70,  42,  23],
        [ 69,  41,  22]],

       [[ 73,  50,  26],
        [ 57,  39,  21],
        [ 54,  41,  28],
        ...,
        [ 72,  45,  24],
        [ 70,  42,  21],
        [ 69,  41,  20]]

# 關閉視窗

In [44]:
cv2.destroyAllWindows()

